# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa9ae36da2e1aa2a30be63e4b477c52991797ccdd3b25d757935b6131b1a2555d13a036f25796fcf93d8f13c869d30a9b1d5378aaa7d4436e3c9827342e40b99

test:
  secret_key_base: 034097574a6a4472cedc1b1624f719433a169e40ba2e34af2eb63826a04d8ef91d300d182b45c1471e92898e48ca35a00db3b7b8d2d6a3509b63b55f457850c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
